### ISSUE TITLE
StreamProcessor rejects large initial volumes of events

### ISSUE THREAD

**Issue by dehora** [zalando-incubator/nakadi-java#100]
When fetching larger number of events, the stream processor fails with a `IllegalStateException`

```
2016-12-06 14:24:10,156 {WARN} [nakadi-java-io] [] [NakadiClient] StreamConnectionRetry: not retryable, propagating error IllegalStateException, more items arrived than were requested
java.lang.IllegalStateException: more items arrived than were requested
	at nakadi.shadow.rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
	at nakadi.shadow.rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:246)
	at nakadi.shadow.rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
```

This happens on the event stream when setting a cursor value like `BEGIN` and being sent a few thousand messages immediately.

**Comment by dehora** [comment]
This looks to be better behaved testing on streams up to 50K events using a begin cursor; closing for now.
