### ISSUE TITLE
StreamProcessor.stop() not shutting down cleanly

### ISSUE THREAD

**Issue by dehora** [zalando-incubator/nakadi-java#186]
Calling `StreamProcessor.stop()` can result in an exception (example below). This can break outside callers that are closing consumers in shutdown hooks (eg Play or Dropwizard).

Example:

```
NakadiClient - stream_processor_err_io Thread[nakadi-java-io-0,5,main], java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@25a7229c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@620b71d3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
nakadi.shadow.io.reactivex.exceptions.UndeliverableException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@25a7229c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@620b71d3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at nakadi.shadow.io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
        at nakadi.shadow.io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:136)
        at nakadi.shadow.io.reactivex.internal.schedulers.ComputationScheduler$EventLoopWorker.schedule(ComputationScheduler.java:211)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutTimedSubscriber.scheduleTimeout(FlowableTimeoutTimed.java:233)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutTimedSubscriber.onNext(FlowableTimeoutTimed.java:223)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:91)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onNext(FlowableDoOnLifecycle.java:79)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUnsubscribeOn$UnsubscribeSubscriber.onNext(FlowableUnsubscribeOn.java:61)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing$UsingSubscriber.onNext(FlowableUsing.java:104)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:181)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:123)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onSubscribe(FlowableOnBackpressureBuffer.java:91)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer.subscribeActual(FlowableOnBackpressureBuffer.java:46)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:73)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
        at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
        at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
        at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@25a7229c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@620b71d3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:549)
        at nakadi.shadow.io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:129)
        ... 32 common frames omitted
```

**Comment by dehora** [comment]
There's been some changes to stop handling in [0.9.0](https://github.com/zalando-incubator/nakadi-java/releases/tag/0.9.0):

- the stop/start/stop sequence will throw an IllegalStateException. There's been a few reports that have come down to this (it causes a RejectedExecutionException). StreamProcessors are not meant to be reusable and this exception clarifies that.

- some internal executor services were not being shutdown properly which may have caused issues with lingering threads/state. Those executors are cleaned up now.

- an error that's harmless but noisy is no longer logged.

0.9.0's a breaking change with 0.8.x. It should also be considered experimental: won't be surprised if it needs a few iterations to .
