### ISSUE TITLE
NakadiClient - retryable_io_eof_exception err=java.io.EOFException

### ISSUE THREAD

**Issue by satybald** [zalando-incubator/nakadi-java#198]
I got EOFException from time to time when open stream via subscription api. Is it expected behavior? 

```
13:43:45.278 [nakadi-java-io-0] WARN NakadiClient - LoggingStreamObserver.onError java.io.EOFException
13:43:45.280 [nakadi-java-io-0] WARN NakadiClient - retryable_io_eof_exception err=java.io.EOFException
java.io.UncheckedIOException: java.io.EOFException
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:574)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorSubscription.fastPath(FlowableFromIterable.java:191)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:123)
	at nakadi.shadow.io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onSubscribe(FlowableOnBackpressureBuffer.java:91)
	at nakadi.shadow.io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:69)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:49)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer.subscribeActual(FlowableOnBackpressureBuffer.java:46)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:73)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:13013)
	at nakadi.shadow.io.reactivex.Flowable.subscribe(Flowable.java:12960)
	at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
	at nakadi.shadow.okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at nakadi.shadow.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:293)
	at nakadi.shadow.okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
	at nakadi.shadow.okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
	at nakadi.shadow.okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at nakadi.shadow.okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
	at nakadi.shadow.okio.InflaterSource.refill(InflaterSource.java:101)
	at nakadi.shadow.okio.InflaterSource.read(InflaterSource.java:62)
	at nakadi.shadow.okio.GzipSource.read(GzipSource.java:80)
	at nakadi.shadow.okio.RealBufferedSource$1.read(RealBufferedSource.java:429)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at nakadi.shadow.okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:251)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at java.io.BufferedReader$1.hasNext(BufferedReader.java:571)
	... 26 common frames omitted
13:43:45.281 [nakadi-java-io-0] INFO NakadiClient - stream_retry_will_sleep sleep=1000 attempt=2/2147483647 thread=nakadi-java-io-0 error=java.io.EOFException
13:43:46.282 [RxComputationThreadPool-3] INFO NakadiClient - LoggingStreamObserver.onStart
13:43:46.282 [RxComputationThreadPool-3] INFO NakadiClient - LoggingStreamObserver.onStop
13:43:46.283 [nakadi-java-io-0] INFO NakadiClient - stream_connection_open step=details mode=subscriptionStream url=https://NAKADI_TEST/subscriptions/30adc239-e407-46be-be3c-3ce2f5736055/events scope=nakadi.event_stream.read
```

Code from the examples:
```
val configuration = new StreamConfiguration()
      .subscriptionId(subscriptonId);
    val processor = nakadiClient
      .resources()
      .streamBuilder(configuration)
      .streamObserverFactory(new LoggingStreamObserverProvider())
      .build()
```

**Comment by satybald** [comment]
Looks like okhttp3 library is not able properly to parse a nakadi response. 

btw I'm using 0.8.5 library.

**Comment by dehora** [comment]
> Looks like okhttp3 library is not able properly to parse a nakadi response.

Looking at this and it seems the Nakadi server is not sending bytes so the client eventually breaks out. I've had related reports in cases where the streams are sparse and not busy - what should be happening in those cases is the server sending keep alive batches to keep the tcp/ip connection active. So this seems this is caused by a server/network issue, and what needs to happen is the client recovers cleanly. 

Can you confirm if the client stops consuming completely or whether it retries in your case?

**Comment by satybald** [comment]
thanks for reply @dehora. Yep, I remember I was testing almost empty stream with no messages incoming. As far as I remember, the client was able to recover from the error. However, I'll need to redo my work to confirm that.

**Comment by dehora** [comment]
Thanks @satybald! Ok if it's recovering that's good to hear; but even in that case the stacktrace is an ops distraction and it looks like this should just be a warning/info message or a metric.

**Comment by dehora** [comment]
There's some improvements in 0.9.0 around retry handling and logging. eof exceptions may get logged but should be recoverable.
