### ISSUE TITLE
unexpected url: /subscriptions?owning_application=YOUR_APP&offset=20&limit=20

### ISSUE THREAD

**Issue by HungUnicorn** [zalando-incubator/nakadi-java#204]
When iterating SubscriptionCollection, this unexpected url exception comes out.

```java
SubscriptionCollection resourceList = client.resources().subscriptions().list(new QueryParams()
                .param("owning_application", application)
        while(resourceList.hasNextLink()) {
            for (Subscription item : resourceList.items()) {
                if (item.consumerGroup().contains(consumerGroup) && item.owningApplication()
                        .equalsIgnoreCase(application)) {
                    subscriptionList.add(item.id());
                }
            }
            resourceList.nextPage();
        }
        return subscriptionList;
```
The normal http call to 
`https://nakadi-live.aruha.zalan.do/subscriptions?owning_application=YOUR_APP&offset=20&limit=20` is fine

The exception:
```java
Exception in thread "main" java.lang.IllegalArgumentException: unexpected url: /subscriptions?owning_application=YOUR_APP&offset=20&limit=20
	at nakadi.shadow.okhttp3.Request$Builder.url(Request.java:142)
	at nakadi.OkHttpResource.prepareBuilder(OkHttpResource.java:198)
	at nakadi.OkHttpResource.requestInner(OkHttpResource.java:164)
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:159)
	at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:168)
	at nakadi.OkHttpResource.lambda$requestThrowing$2(OkHttpResource.java:97)
	at nakadi.OkHttpResource$$Lambda$22/91912419.call(Unknown Source)
	at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32)
	at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842)
	at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727)
	at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:97)
	at nakadi.SubscriptionResourceReal.loadPage(SubscriptionResourceReal.java:260)
	at nakadi.SubscriptionCollection.fetchPage(SubscriptionCollection.java:21)
	at nakadi.ResourceCollection.nextPage(ResourceCollection.java:72)
```

**Comment by dehora** [comment]
@HungUnicorn it looks like the Nakadi server is sending back relative links. I'm going to try and patch the client for now, but I'd encourage you to file an issue upstream with Nakadi to send back absolute links as that simplifies client engineering.

**Comment by HungUnicorn** [comment]
Sounds reasonable, created here
https://github.com/zalando/nakadi/issues/682

**Comment by dehora** [comment]
0.8.8 has a patch for this, lmk if that works for you

**Comment by dehora** [comment]
closing via 0.8.8
